language: python
python:
  - '3.5'
services:
  - postgresql
addons:
  postgresql: "9.4"
install: pip install -r requirements.txt
before_script:
  - psql -c 'create user teamfinder with CREATEDB;' -U postgres
  - psql -c 'create database teamfinder owner teamfinder;' -U postgres
  - echo "SECRET_KEY = 'foo'" > api/teamfinder/settings_local.py
  - cd api
  - python manage.py migrate
script:
  - python manage.py test -v 2
deploy:
  - provider: script
    script: scripts/start_deploy.sh
    on:
      branch: master

