language: python
python:
  - '3.5'
install: pip install -r requirements.txt
before_script:
  - echo "SECRET_KEY = 'foo'" > teamfinder/settings_local.py
  - python manage.py migrate
script:
  - python manage.py test -v 2
deploy:
  - provider: script
    script: scripts/start_deploy.sh
    on:
      branch: master

