version: '3'

services:
  db:
    image: postgres
    env_file:
      - ./api/docker/.db.env
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: ./api/docker/Dockerfile
    volumes:
      - .:/code
    depends_on:
      - db
    command: python3 api/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: unless-stopped
